language: python
language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - travis_wait 600 python ./code/style_transfer.py --train ./data/yelp/sentiment.train --dev ./data/yelp/sentiment.dev --output ./tmp/sentiment.dev --vocab ./tmp/yelp.vocab --model ./tmp/model 
